### ISSUE TITLE
data loading perf

### ISSUE THREAD

**Issue by LittleLittleCloud** [chausner/ArffTools#2]
Firstly, Thanks for creating this arff tool, it's awesome.

I am seeking a way to convert arff to csv format and I find out that on some large dataset it may costs a lot of time to load the entire dataset. For example, in the following dataset, it costs me about 1 hr when calling `ReadAllInstances`. FYI, my machine is a surface book 2 i7 32GB laptop.

- https://www.openml.org/d/41147

Is there any efficient way to make the loading speed much faster? Thanks

**Comment by chausner** [comment]
For converting to CSV, you don't need to load/keep all instances in memory. You can do something like this:
```csharp
using (ArffReader arffReader = new ArffReader("glass.arff"))
{
    ArffHeader header = arffReader.ReadHeader();    
    object[] instance;    
    while ((instance = arffReader.ReadInstance()) != null)
    {
        // write instance to CSV file
    }    
}
```

This should at least consume much less memory, it might still take some time for very large datasets, however.
